### ISSUE TITLE
Standardise .README structure

### ISSUE THREAD

**Issue by xzilja** [rnc-archive/template#4]
Looking at various repos, it is clear that README files don't follow common structure. I feel like users would benefit a lot if we define specific sections for README files like `Installation / Example / API / Requirements ...` and order them in same manner. This will mean that anyone familiar with other packages in react native community will be familiar with readme's and able to find what they are looking for faster.

We should also try to stick with same formatting where possible.

**Comment by kelset** [comment]
Also, found this https://github.com/kefranabg/readme-md-generator which may help / give a good other source of inspiration
